version: '3'

networks:
  backend:
    driver: bridge

services:
    rumour_spreading_mongo:
        container_name: rumour_spreading_mongo
        build: 
            context: .
            dockerfile: ./mongo/Dockerfile
            args:
                # there are many rumour topics in zip file that will be download in Dockerfile
                # can choose with this list
                # charliehebdo, ebola-essien, ferguson, germanwings-crash, ottawashooting, prince-toronto, putinmissing, sydneysiege
                # if would like to change this value need to run `up --build` once, for re-build docker image
                RUMOUR_TOPIC: ${RUMOUR_TOPIC}
        restart: always
        volumes:
            # persistant location
            - ./mongo/data:/data/db
            # init script
            - ./mongo/init.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro 
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
